baseURL = 'https://antidanyar.github.io/academic/'
languageCode = 'en-us'
title = "Daniar Kasenov's personal page"
theme = "PaperMod"
sectionPagesMenu = 'main'

[menu]
[[menu.main]]
  name = 'About'
  pageRef = '/'
  weight = 10
[[menu.main]]
  name = 'Talks'
  pageRef = '/Talks'
  weight = 30
[[menu.main]]
  name = 'Papers'
  pageRef = '/Papers'
  weight = 20
[[menu.main]]
  name = 'CV'
  pageRef = '/curvit'
  weight = 40